### ISSUE TITLE
Person Detection

### ISSUE THREAD

**Issue by murilovarges** [mostafa-saad/deep-activity-rec#18]
Hi @mostafa-saad,  

I would like to know how do you perform person detection given a frame, I already read the paper and understood the person tracking using "Dlib Video Tracking Object". However to perform feature extraction and classification in the test step you need firstly detect people in a given video frame.

**Comment by vishveshsoni** [comment]
@murilovarges you can train RCNN or YOLO model for the object detection and inference on frame by frame. I would suggest you to try transfer learning to increase the accuracy. Moreover, instead of doing classification of each object, you should try LRCN (Long-term Recurrent Convolutional Networks- https://arxiv.org/abs/1411.4389 ) similar to @mostafa-saad  approach for action recognition.

**Comment by murilovarges** [comment]
Thanks, @vishveshsoni for the answer. But I would like to know how @mostafa-saad did the person detection for comparative studies and results. I don't know if he used the annotations um the test phase since  I don't found this information on the paper.

**Comment by mostafa-saad** [comment]
We used the frame given by the annotation. We tracked it in the clip.

**Comment by murilovarges** [comment]
Thanks, @mostafa-saad for the answer.
