### ISSUE TITLE
Not exist directory

### ISSUE THREAD

**Issue by bbliao** [mostafa-saad/deep-activity-rec#2]
@mostafa-saad 
I tried to run “script-simple.sh” as you told, then I found Phase1 and Phase 2 is ok, but Phase 3 reports “p4-network2/trainval-leveldb: does not exist”.

I tried to run “script-clean.sh”, but the same problem exists.
Could you please help me how to fix it? Thank you very much.

Best wishes
Binbing

[script-simple-expected-log.txt](https://github.com/mostafa-saad/deep-activity-rec/files/491500/script-simple-expected-log.txt)
[z_log_dataset_net2.txt](https://github.com/mostafa-saad/deep-activity-rec/files/491501/z_log_dataset_net2.txt)
[z_trainval-test-log.txt](https://github.com/mostafa-saad/deep-activity-rec/files/491502/z_trainval-test-log.txt)
[z_trainval-test-window-evaluation-log-prop.txt](https://github.com/mostafa-saad/deep-activity-rec/files/491503/z_trainval-test-window-evaluation-log-prop.txt)

**Comment by mostafa-saad** [comment]
Hi,

The actual problem is in the z_log_dataset_net2.txt. The log has run time error, next step was to load Caffe network. As that step failed, the leveldb dataset directory was not created and further steps failed.

I can duplicate the issue on my side. It is so weird. It seems somehow a makefile problem. In my environment, I was actually working with eclipse, then I wrote the makefile in the repository. I am not makefile guys :(

When i do some workaround and uses the eclipse generated makefile, process completes correctly!

So overall it is makefile problem. I will put more time to know why my makefile is wrong. Temporarily, if you can rewrite the makefile by yourself or Create eclipse project and let it generate a makefile, the problem should be solved.

**Comment by mostafa-saad** [comment]
@bbliao

In lap computer, I encountered this error again (RTE while creating network). It turned out because of leveldb. When I made sure shell file see specific version of leveldb libraries, it worked well.

However, trying that in that project file did not help.

On the other side, I tried this project on my personal laptop (where one version of every library installed), it worked perfectly.

So overall, problem is not solved globally. Seems more about consistency in leveldb/boost include/libs.

**Comment by pribadihcr** [comment]
I also has the same issue

**Comment by hejiaoyu** [comment]
I also has the same issue

**Comment by hejiaoyu** [comment]
@bbliao 
Excuse me, I met the same issue. Do you fix that?

**Comment by mostafa-saad** [comment]
It is a makefile problem. Specifically, I am not good in writing makefiles. When I put the project in eclipse, it works well. But using my makefile, fails in the 3rd phase.

**Comment by pribadihcr** [comment]
@mostafa-saad ,

So, do you have step by step documentation to run it using eclipse ?
Thanks

**Comment by mostafa-saad** [comment]
@bbliao  @pribadihcr  @hejiaoyu 

I tried again whole day and failed to fix my makefile. Time for a workaround.
-------------------
- As said, the makefiles of my eclipse projects generate it correctly
- I uploaded the eclipse project at: /eclipse-project/ibrahim16-deep-act-rec-part
- We will use this project to generate the 3 EXEs instead of my makefile
- Compile using the normal makefile. This ensure your environment is correct.
- This process generates 3 EXEs for 4 phases: exePhase1_2, exePhase3, exePhase4
-----------------------
- Now, let's compile and build the eclipse project 3 times.
- 3 files to fix their includes paths and others
-- eclipse-project/ibrahim16-deep-act-rec-part/Release/makefile
-- eclipse-project/ibrahim16-deep-act-rec-part/Release/src/subdir.mk
-- eclipse-project/ibrahim16-deep-act-rec-part/Release/apps/subdir.mk
- For apps/subdir.mk, you will change it 3 times for 3 EXEs
-- You will find it for now on exePhase3.
-- In 2nd time compile exePhase4
-- You don't actually to compile it for exePhase1_2 (so just 2 EXEs to replace)
- To compile, just go to clipse-project/ibrahim16-deep-act-rec-part/Release
-- make command for build
-- make clean for cleaning
- Each time an exeutable is generated. Reneame to its phase (e.g. exePhase3) and replace the exe at deep-activity-rec level

That is all

**Comment by pribadihcr** [comment]
HI @mostafa-saad,

I use the eclipse-project. For ibrahim16-cvpr-simple it succeed. But for ibrahim16-cvpr still fail into the same error:
Phase 4 - B - Temporal Evaluation
20:38:17.292364 11584 exePhase4.cpp:252] Make sure to have LD_LIBRARY_PATH pointing to LSTM implementation in case of LSTM
E0303 20:38:17.292753 11584 exePhase4.cpp:146] Temporal Window = 10
E0303 20:38:17.292778 11584 exePhase4.cpp:153] Using GPU
E0303 20:38:17.292793 11584 exePhase4.cpp:154] Using Device_id = 0
E0303 20:38:17.729176 11584 exePhase4.cpp:166] Model: examples/deep-activity-rec/ibrahim16-cvpr/p4-network2/z_snapshot_iter_20000.caffemodel
E0303 20:38:17.729228 11584 exePhase4.cpp:167] Proto: examples/deep-activity-rec/ibrahim16-cvpr/p4-network2/trainval-test-window-evaluation-network.prototxt
E0303 20:38:17.729259 11584 exePhase4.cpp:169] Creating the test network
F0303 20:38:17.732589 11611 db_leveldb.cpp:16] Check failed: status.ok() Failed to open leveldb examples/deep-activity-rec/ibrahim16-cvpr/p4-network2/test-leveldb
Invalid argument: examples/deep-activity-rec/ibrahim16-cvpr/p4-network2/test-leveldb: does not exist (create_if_missing is false)
*** Check failure stack trace: ***
    @     0x7f843b930daa  (unknown)
    @     0x7f843b930ce4  (unknown)
    @     0x7f843b9306e6  (unknown)
    @     0x7f843b933687  (unknown)
    @     0x7f843ae83d07  caffe::db::LevelDB::Open()
    @     0x7f843ae37463  caffe::DataReader::Body::InternalThreadEntry()
    @     0x7f843aea0cc5  caffe::InternalThread::entry()
    @     0x7f842e213a4a  (unknown)
    @     0x7f843a9df184  start_thread
    @     0x7f8439edd37d  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)


DONE processing script ./script.sh

**Comment by mostafa-saad** [comment]
@pribadihcr 
Can you attach all generated txt/log files?

**Comment by pribadihcr** [comment]
ibrahim16-cvpr p4-network2 log:

[z_log_dataset_net2.txt](https://github.com/mostafa-saad/deep-activity-rec/files/816852/z_log_dataset_net2.txt)
[z_trainval-test-log.txt](https://github.com/mostafa-saad/deep-activity-rec/files/816853/z_trainval-test-log.txt)
[z_trainval-test-window-evaluation-log-prop.txt](https://github.com/mostafa-saad/deep-activity-rec/files/816854/z_trainval-test-window-evaluation-log-prop.txt)

**Comment by mostafa-saad** [comment]
@pribadihcr 
all logs of all folders. these logs seems means the database is not crated.

**Comment by pribadihcr** [comment]
[z_log_dataset_net1.txt](https://github.com/mostafa-saad/deep-activity-rec/files/816873/z_log_dataset_net1.txt)
[z_trainval-test-log.txt](https://github.com/mostafa-saad/deep-activity-rec/files/816874/z_trainval-test-log.txt)
[z_log_dataset_fuse.txt](https://github.com/mostafa-saad/deep-activity-rec/files/816876/z_log_dataset_fuse.txt)
[z_log_dataset_net2.txt](https://github.com/mostafa-saad/deep-activity-rec/files/816877/z_log_dataset_net2.txt)
[z_trainval-test-log.txt](https://github.com/mostafa-saad/deep-activity-rec/files/816878/z_trainval-test-log.txt)
[z_trainval-test-window-evaluation-log-prop.txt](https://github.com/mostafa-saad/deep-activity-rec/files/816879/z_trainval-test-window-evaluation-log-prop.txt)

in folder p3-extract-features-networks there is no logs

**Comment by mostafa-saad** [comment]
@pribadihcr 
Have you edited the scripts? Phase 3 now doesn't face old error (failing to create/load caffe network). Seems the script doesn't go well

Failed to convert string: [/home/deep307/CVPR/group_activity/caffe-lstm/examples/deep-activity-rec/ibrahim16-cvpr/p4-network2/trainval-leveldb] to same type as variable [1]
exePhase3: ../src/utilities.h:98: Type MostCV::toType(std::string, Type, std::string) [with Type = int; std::string = std::basic_string<char>]: Assertion `false' failed.

It seems problem in passing parameters from the script.

**Comment by pribadihcr** [comment]
no, the same like in the simple one. But why the simple works

**Comment by mostafa-saad** [comment]
May you try to print the values passed to phase 3?
Search for "echo Phase 3 - Generating LSTM 2 Data" in script

May you upload your script file?

**Comment by hejiaoyu** [comment]
@mostafa-saad
I had a try, ibrahim16-cvpr still fail into the same error.

[script-p1-train-p3-p4.txt](https://github.com/mostafa-saad/deep-activity-rec/files/847487/script-p1-train-p3-p4.txt)
this is the script file.

**Comment by mostafa-saad** [comment]
@hejiaoyu 

I am suspecting variable $FUSION_LAYERS is not resolved correctly in your shell version (although simple script works!)

Anyway, let's try this manually

Replace
$FUSION_LAYERS
with
2 fc7 lstm1

**Comment by qdinfish** [comment]
Hi,

I updated 3 files and whether the objects.mk need update?(I updated it.) 
-- eclipse-project/ibrahim16-deep-act-rec-part/Release/makefile
-- eclipse-project/ibrahim16-deep-act-rec-part/Release/src/subdir.mk
-- eclipse-project/ibrahim16-deep-act-rec-part/Release/apps/subdir.mk

I run "make" in the eclipse project's directory  "-- eclipse-project/ibrahim16-deep-act-rec-part/Release". 
Then get the following error. :( How can I do? thanks a lot.


======log=========

finished building: ../apps/exePhase3.cpp
 
Building target: ibrahim16-deep-act-rec-part
Invoking: GCC C++ Linker
g++ -L/home/jichaol/dlib/ -L/home/jichaol/caffe-lstm/build/lib -L/usr/lib -L/home/jichaol/dlib/examples/build/dlib_build -o "ibrahim16-deep-act-rec-part"  ./src/dlib-tracker-wrapper.o ./src/images-utilities.o ./src/leveldb-reader.o ./src/leveldb-writer.o ./src/rect-helper.o ./src/utilities.o ./src/volleyball-dataset-mgr.o  ./apps/exePhase3.o  /home/jichaol/dlib/tools/python/build/dlib_build/libdlib.a -lprotobuf -lopencv_core -lopencv_highgui -lopencv_imgproc -lopencv_ml -lgflags -lleveldb -lglog -lboost_system -lboost_filesystem -lboost_chrono -lboost_python -lpython2.7 -lcaffe
/usr/bin/ld: /home/jichaol/dlib/tools/python/build/dlib_build/libdlib.a(threads_kernel_2.cpp.o): undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
makefile:46: recipe for target 'ibrahim16-deep-act-rec-part' failed
make: *** [ibrahim16-deep-act-rec-part] Error 1

**Comment by mostafa-saad** [comment]
@jichaoliu 
It is a linking problem. Seems something missing in installed libraries in your environment. 
The error seems popular on web. Kindly, see if that helps.
