### ISSUE TITLE
Volleyball videos

### ISSUE THREAD

**Issue by Peratham** [mostafa-saad/deep-activity-rec#3]
Hi @mostafa-saad ,

I would like to request the raw video files for Youtube volleyball. Is it possible to include the raw videos and how to extract the keyframes from them (before manual selection)?

Thanks,
Peratham

**Comment by mostafa-saad** [comment]
If you have the raw videos, what other things you may extract from it?!

**Comment by mostafa-saad** [comment]
I think you can extract that from the given temporal window per a frame instance.

The problem, I tried to redownload the videos using the parameters my college Sirkanth mentioned and videos are not 100% same. So I am stuck in that. Not sure if this is due to Youtube changing things on their sides or not. I will give a trial one more time. Meanwhile, we won't be able to offer a link to the videos themselves.

**Comment by Peratham** [comment]
ok. thanks!!
